title: Sky Music
description: Visual music sheets for the game Sky Children of the Light
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
plugins:
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
collections_dir: songs
collections:
  - anime
  - classical
  - movies
  - popular
  - original_player_song
  - traditional
  - videogames
